### ISSUE TITLE
Webpack 5 support?

### ISSUE THREAD

**Issue by mxhCodes** [christophersmith262/drupal-libraries-webpack-plugin#15]
Hello, I wanted to try this plugin out, but it seems it doesn't work with Webpack 5. I shortly tried it by using Symfony Webpack Encore. It failed with the following error when trying to run the build:

```TypeError: Cannot read property 'tap' of undefined```

**Comment by yannickoo** [comment]
Hey @mxhCodes you can check my PR that makes this plugin compatible with Webpack 5 now 🎉

**Comment by mxhCodes** [comment]
Thanks, last year I was implementing a module for my needs (only works with Symfony's Webpack Encore though): https://www.drupal.org/project/entrypoints

**Comment by danielamorse** [comment]
v2 now supports Webpack 5. Thanks for the PR @yannickoo!
